### PR TITLE
346 add unit testing to mentee completion and mentee display

### LINKED ISSUE #346: Add unit testing for MenteeCompletion.js and MenteeDisplay.js

### PR DESCRIPTION
**Pull request by katmartel**
My work on this has been a little choppy due to the power outages, but it looks like BC Hyrdo *finally* fixed the outages, so hopefully it'll be smooth from here on out. I've tried my best to identify logical tests, and based on what I've done, they've passed. So, I'm hoping everything is correct.

One point that I hope to address: the console gives a warning. I'm not too sure how to fix it, but I'm hoping to re-look at it once my brain isn't so muddled.

### CODE REVIEW

**Review by jpabadir — APPROVED** [review]
I fixed the warning. Feel free to look at my commit and ask if you have any questions.

**Comment by katmartel** [comment]
> I fixed the warning. Feel free to look at my commit and ask if you have any questions.

Thank you!! I was hoping to circle back to this later tonight, but I really appreciate that you looked at it. Now that I see what you've done, the warning message makes more sense.

[Per our new convention](https://discord.com/channels/756399767457628171/760858810398801970/797830918504185866), I'll wait until 24hours have passed on this PR until I merge (if I'm able to resolve the CI fail before the 24hrs) :)

**Review by aleksssk — APPROVED** [review]
Nice work

**Review by wrc9817 — APPROVED** [review]

**Comment by wrc9817** [comment]
Don't forget to resolve conflicts tho.

**Pull request merged**
