### PR TITLE
THIS PR IS OBSOLETE, PLEASE DO NOT REVIEW, DO NOT WORK - issue 185 - split form into two parts, and create create account page

### LINKED ISSUE #185: DO NOT WORK ON THIS - Front End - Split form into Two Sections & add 'Create Account' function - Create content
Based on the static form from last week's sprint, remove the 'Submit' button from that section. When the 'next' button is clicked, go to another page for the user to fill in information to create an account. Once the user clicks 'submit', that information will be sent to the database.
Fix Email and User type fields, add ranked skills (3 input fields, the drop-down options should be hardcoded).

### LINKED ISSUE #240: DO NOT WORK ON THIS - Add logic to "next" button
Button on the form should switch between first page and second page of create account contents and mentorship form contents. 

We think routing may not be the ideal solution, some exploration will need to be needed around how to implement this "progress form".

### PR DESCRIPTION
**Pull request by aleksssk**
Finished issue 185, tested on browser and everything runs properly

### CODE REVIEW

**Review by jpabadir — COMMENTED** [review]
There may have been a bit of miscommunication on this task. As it stands, I think good progress has been made on it but it is not yet finished. Let's chat about it at today's meeting.

**Review by katmartel — APPROVED** [review]
Nice work!

**Comment by jpabadir** [comment]
I think the need for this PR is obsolete since we do not want to separate the form into two anymore. Some of the code of this PR, however (namely choosing skills) is still relevant. I think we should close issue #240, and pivot issue #185 to be "Add ranked skills", and ask Aleks to "start over" on this PR, keeping only the skills adding code he wrote, after we merge PR #255. @KatrinaMart and @aleksssk, is that fair?

**Comment by katmartel** [comment]
> I think the need for this PR is obsolete since we do not want to separate the form into two anymore. Some of the code of this PR, however (namely choosing skills) is still relevant. I think we should close issue #240, and pivot issue #185 to be "Add ranked skills", and ask Aleks to "start over" on this PR, keeping only the skills adding code he wrote, after we merge PR #255. @KatrinaMart and @aleksssk, is that fair?

In one of my comments on Eric's PR (#255), I referenced Aleks' work that he'd done on the skills inputs since it's definitely important that we ensure that gets incorporated. Creating a new PR with for the relevant form fields sounds fair!

**Review by wrc9817 — APPROVED** [review]

**Comment by jpabadir** [comment]
Closing as obsolete.

**Pull request closed without merging**
