### PR TITLE
Save fields from mentor and mentee signup forms into the DB

### LINKED ISSUE #243: Save all info from signup form into firebase

### PR DESCRIPTION
**Pull request by jpabadir**

### CODE REVIEW

**Comment by jpabadir** [comment]
Close #243

**Comment by jpabadir** [comment]
Close #243

**Comment by jpabadir** [comment]
close #243

**Review by katmartel — APPROVED** [review]
Awesome! Thank you for setting this up!

**Review by aleksssk — APPROVED** [review]
Looks good!

**Review by wrc9817 — APPROVED** [review]
Nice!

**Pull request merged**
