### PR TITLE
issue 246 - refine mentor UI

### LINKED ISSUE #246: Refine the mentor UI to show proper information about accepted mentees
There will be sample data being pulled from the DB for you to display.

### LINKED ISSUE #272: React routing UI for mentor form
Create react routing UI/Setup for the mentor UI

### PR DESCRIPTION
**Pull request by aleksssk**
Created a ui for the mentor home, added 3 new UI's for suggested, pending, accepted mentees and also made a simple home UI for the mentor home. (I made buttons on the mentor home to go to the suggested, pending, and accepted mentees, but I can not figure out how to get the react routing to work (I have tried for about an hour)

### CODE REVIEW

**Review by jpabadir — CHANGES_REQUESTED** [review]
This is a good start. However, there are some issues: 
1. As per our November 15 conversation on Discord, this task entails copy-pasting the sample data I added in the sample-data.json file into the state of the component and writing the logic that goes along with pulling those values into your UI to show them. 
2. This PR has a lot of repeated code. That's a sign that the "card" should be made into a component, which take props to display the right values. 
3. Though it does not block user flow, let's try to fix the error below. 
Screen Shot 2020-11-16 at 2 50 32 PM

**Review by katmartel — COMMENTED** [review]
We'll probably discuss this during the meeting: But what's the difference between a pending mentor versus a suggested mentor? From what I can tell, they look the same?
Is routing necessary, or could we stick to one page for the mentor UI for simplicity?

**Comment by jpabadir** [comment]
Update during meeting: 

This PR will now be focused on issue 272. This is now a routing-focused PR. Instead of all the repeated code for the cards, please render a simple component for each of the two routes made up of one single h1 that describes. You can keep the components you've already made (Suggested and Approved Mentor) but remove the "card" code from there, keeping only an h1 for each. 
Also get rid of the whole pending mentor component and its tab.

**Review by katmartel — APPROVED** [review]
Thanks for incorporating the modifications that we discussed during the meeting!

**Pull request merged**
