### PR TITLE
Pull mentees into mentor ui

### LINKED ISSUE #244: Pull matched mentees into mentor UI
There will be sample data (sample matched mentees) added to the database to be pulled into the front-end

### PR DESCRIPTION
**Pull request by jpabadir**

### CODE REVIEW

**Comment by jpabadir** [comment]
Sorry for deleting all your comments explaining fragments, @KatrinaMart, but I was able to very quickly find info about fragments by googling "what is <> react", so I think it's a bit redundant to have comments about it in multiple places throughout the code. Let me know if you feel strongly about this. :)

**Comment by katmartel** [comment]
> Sorry for deleting all your comments explaining fragments, @KatrinaMart, but I was able to very quickly find info about fragments by googling "what is <> react", so I think it's a bit redundant to have comments about it in multiple places throughout the code. Let me know if you feel strongly about this. :)

No worries! There's no need for the same comment in multiple locations, so it's completely fine to have removed 👍

**Review by katmartel — APPROVED** [review]
Great work, this is really cool!

**Review by wrc9817 — APPROVED** [review]
Nice job

**Review by aleksssk — APPROVED** [review]
Looks good

**Comment by jpabadir** [comment]
close #293

**Pull request merged**
