### PR TITLE
377 block unverified users

### PR DESCRIPTION
**Pull request by aleksssk**
Block unverified users from singing in

### CODE REVIEW

**Review by jpabadir — APPROVED** [review]
If you can test this to make sure it works before you merge, that would be awesome. Thanks!

**Review by aleksssk — COMMENTED** [review]
I just reviewed the code, but when I sign in with a verified email and then switch between the mentor tutorial/suggested mentees/accepted mentees I can see the "please verify your email to access your account" page for a quick second, even though the email is already verified. It seems like it is loading that page before loading the suggested mentee page, etc. Should we try to fix this? Maybe making a window alert would fix this?

Also if I sign in with an unverified email address it brings me to the page that says "please verify your email to access your account" but then I can not get back to the original login screen. Every time I click on the login tab it just brings me back to the "please verify your email to access your account". Also the logout button is gone from that page so I can't log out to see the login screen again.

What I had on the login page worked but, the only problem was that if the user was unverified it would still bring them to the mentor home page (But a pop up that says please verify your email would show up). I just couldn't figure out how to stop it from redirecting from the login page to the mentor home page. I tried using break but it still did not work.

**Review by aleksssk — COMMENTED** [review]
In my opinion if we can use my code I wrote but got it to not redirect to the mentor home page that would work well. But I'm not too sure how hard it is to work with my code and then make it not redirect to the other page.

**Comment by jpabadir** [comment]
There were issues with your previous implementation, I think it'll be easier to solve with the way I did. If you feel strongly about this and disagree with me, write me a DM on Discord, we can talk. I will say, however, that I strongly believe my implementation is the way to go. I can tell you why at the next meeting, if you want to know. 

I'm aware of the issue you're describing when switching tabs. I opened [an issue](https://github.com/jpabadir/pace-c/issues/394) for us to fix it. This problem predates the code we did today, and needs to be fixed independently of that, because it's always been doing that, we just didn't see it as much before.

The part where I agree with you is that it's not good to not be able to logout when we're in the unverified but logged in state. Can you work on this? The right way of doing it IMO is to merge develop in this branch, and use the new functionality I made with the dynamic top right menu to enable the user to logout when needed.

**Review by aleksssk — COMMENTED** [review]
sounds good! either way works for me, I was just not sure which would be easier. And yea, I will give trying to merge develop into the branch a go! thanks for helping!

**Comment by aleksssk** [comment]
Made another pull request.

**Pull request closed without merging**
